name: build-all

on:
  workflow_dispatch:
    inputs:
      git-address:
        description: 'git-address'
        required: true
        default: 'https://github.com/buildroot/buildroot.git'
      branches-tags:
        description: 'branches-tags'
        required: true
        default: '2024.02.1'
      board:
        description: 'board'
        required: true
        default: 'a30'
      custom-config:
        description: 'custom-config'
        required: false
        default: 'a30_defconfig'
      build-with:
        description: 'build-with'
        required: false
        default: ''
      create-release:
        description: 'create release'
        required: false
        default: 'false'


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v2
    - name: Clone source code
      run: |
        git clone ${{github.event.inputs.git-address}} /opt/buildroot
        cd /opt/buildroot

    - name: Install packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y make gcc g++ unzip git bc python3 device-tree-compiler mtd-utils gcc-multilib g++-multilib

    - name: Bulid
      run: |
        mkdir /opt/firmware
        cd /opt/buildroot
        git checkout ${{github.event.inputs.branches-tags}}
        git pull origin ${{github.event.inputs.branches-tags}}

        if [ ${{github.event.inputs.custom-config}}!='' ]; then cp -f /home/runner/work/buildroot-actions/buildroot-actions/configs/${{github.event.inputs.custom-config}} configs/; fi

        CPU_N=$(getconf _NPROCESSORS_ONLN)

        echo '---start make---'
        echo 'CPU: ${CPU_N}'
        make ${{github.event.inputs.board}}_defconfig
        set -o pipefail
        if ! ( \
        make -j $CPU_N 2>&1 \
        | tee build.log \
        | grep ">>>" \
        ); then tail -n100 build.log && exit 1
        fi
        make sdk
        ls -lah /opt
        gzip /opt/buildroot/output/images/rootfs.tar
        cp /opt/buildroot/configs/${{github.event.inputs.board}}_defconfig /opt/buildroot/output/images/
    - name: Archive build logs
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-logs
        path: /opt/buildroot/build.log

    - name : Upload buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
      uses: actions/upload-artifact@master
      with:
        name: buildroot-${{github.event.inputs.branches-tags}}-${{github.event.inputs.board}}
        path: /opt/buildroot/output/images
        if-no-files-found: error

    - name: Release with Notes
      uses: softprops/action-gh-release@v1
      if: contains(github.event.inputs.create-release, 'true')
      with:
        tag_name: ${{github.event.inputs.board}}
        files: |
           /opt/buildroot/output/images/arm-a30-linux-gnueabihf_sdk-buildroot.tar.gz
           /opt/buildroot/output/images/rootfs.tar.gz
           /opt/buildroot/configs/${{github.event.inputs.board}}_defconfig
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
